### ISSUE TITLE
Text is off screen and buttons half visible on Media page 

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/commentpress-mla#9]
If adding media to a comment, a tab opens with a rather misaligned screen. 
![screen shot 2015-03-04 at 3 45 49 pm](https://cloud.githubusercontent.com/assets/7083891/6493032/cd357e96-c285-11e4-94b5-74870ab301fd.png)

**Comment by christianwach** [comment]
You may wish to revisit this, since it was [fixed upstream a while ago](https://github.com/IFBook/commentpress-core/blob/master/themes/commentpress-theme/assets/css/screen-default.css#L4307). Indeed, setting screen reader text to `display: none` means that it is no longer available as text to screen readers!

**Comment by chriszarate** [comment]
Indeed! Thanks!
